### ISSUE TITLE
Mention accessibility concerns somewhere 

### ISSUE THREAD

**Issue by mybearworld** [Secret-chest/fancify-text#1]
Accessibility is a problem with these "fonts", as they are actually Unicode characters with different meanings and screen readers read them out with those meanings, not the letters they look like.

**Comment by mybearworld** [comment]
> I might need to see which ones do that though, as the bold/italic/mono/etc ones are probably being read correctly

As far as I know, the monospace example would be read as something like "`Mathematical monospace character capital H` `Mathematical monospace character small L` `Mathematical monospace character small L` `Mathematical monospace character small O`".

**Comment by Secret-chest** [comment]
I'm doing it soon.
