### ISSUE TITLE
License this code

### ISSUE THREAD

**Issue by Secret-chest** [Secret-chest/fancify-text#5]
@nottrobin would you license this code? I was completely stupid when I accepted your contributions lol. Currently there's no licence, can you apply one?

**Comment by nottrobin** [comment]
You're welcome to license the code however you want. I'm not precious about it. I tend to make my work public domain, but I don't mind if you want to retain more control than that. Feel free to take it.

**Comment by Secret-chest** [comment]
Alright, when I get home I will apply CC0.
